apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: default
spec:
  replicas: 1 # Tek bir MongoDB Pod'u çalýþtýrýyoruz
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      securityContext: # Pod'un güvenlik ayarlarý root user (administrator) olarak çalýþmasýný saðlýyor.
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: mongo
          image: mongo:latest # En son MongoDB imajýný kullanýyoruz
          ports:
            - containerPort: 27017 # MongoDB'nin kullandýðý port
          volumeMounts:
            - name: mongo-volume
              mountPath: /data/db # MongoDB konteyneri içindeki veri yolu
      volumes:
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: mongo-pvc # PVC'yi Pod'a baðlýyoruz
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  type: ClusterIP
  ports:
    - name: http
      port: 27017
      protocol: TCP
      targetPort: 27017
