apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce # PV ile ayný eriþim modunu kullanmalý
  resources:
    requests:
      storage: 20Gi # PV ile ayný boyutta depolama alaný talep ediyoruz