apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: Ym9ubGluZXN0b3JlX2FkbWlu # bonlinestore_admin
  mongo-root-password: U2NhZzE4NjQ4OQ== # Scag186489
  mongo-init-database: YWRtaW4= # admin
