# Template docker-push

# This template allows you to build and push your docker image to a Docker Hub account.
# The workflow allows running tests, code linting and security scans on feature branches (as well as master).
# The docker image will be validated and pushed to the docker registry after the code is merged to master.

# Prerequisites: $DOCKERHUB_USERNAME, $DOCKERHUB_PASSWORD setup as deployment variables

image: atlassian/default-image:3

pipelines:
  custom:
    definitons:
        - step:
            name: Definitons Service Publish Docker Hub
            script:              
              - docker login -u scakir1978 -p Scag185489
              - docker-compose build definitions.bonlinestore.com
              - docker push scakir1978/definitions.bonlinestore.com:latest
            services:
              - docker            
    identity:
        - step:
            name: Identity Service Publish Docker Hub
            script:              
              - docker login -u scakir1978 -p Scag185489
              - docker-compose build identity.bonlinestore.com
              - docker push scakir1978/identity.bonlinestore.com:latest
            services:
              - docker            
    production:
        - step:
            name: Production Service Publish Docker Hub
            script:              
              - docker login -u scakir1978 -p Scag185489
              - docker-compose build production.bonlinestore.com
              - docker push scakir1978/production.bonlinestore.com:latest
            services:
              - docker            
    ui:
        - step:
            name: UI Publish Docker Hub
            script:              
              - docker login -u scakir1978 -p Scag185489
              - docker-compose build ui.bonlinestore.com
              - docker push scakir1978/ui.bonlinestore.com:latest
            services:
              - docker
definitions:
  services:
    docker:
      memory: 2048  # reduce memory for docker-in-docker from 1GB to 512MB
