version: '3.8'

services:
  mongodb:
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:    
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Scag18548912345*

  identitydbdocker:
    container_name: identitydbdocker
    user: root
    restart: always
    ports:
      - "1444:1433"
    volumes:
      - identity_data:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Scag18548912345*

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"    

  seq:
    container_name: seq
    restart: always
    ports:      
      - "5341:80"
    volumes:
      - seq_data:/data
    environment:
      - ACCEPT_EULA=Y        

  identity.bonlinestore.com:
    container_name: identity.bonlinestore.com
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - "IdentityServerUrl=https://identity.bonlinestore.com"
      - "ConnectionStrings:DefaultConnection=Server=identitydbdocker,1433;Database=IdentityDB; User=sa; Password=Scag18548912345*"
      - "IdentityConfigSettings:RedirectUri=https://ui.bonlinestore.com/pages/callback"
      - "IdentityConfigSettings:AllowedCorsOrigin1=https://ui.bonlinestore.com"
      - "IdentityConfigSettings:AllowedCorsOrigin2=https://gateway.bonlinestore.com"
      - "IdentityConfigSettings:PostLogoutRedirectUri=https://ui.bonlinestore.com/pages/callout"
      - "IdentityConfigSettings:FrontChannelLogoutUri=https://ui.bonlinestore.com/pages/callout"
      - "IdentityRunningMode=docker"
    depends_on:
      - "identitydbdocker"    

  definitions.bonlinestore.com:
    container_name: definitions.bonlinestore.com
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80      
      - "DatabaseSettings:ConnectionString=mongodb://mongodb:27017"
      - "IdentityServerUrl=https://identity.bonlinestore.com"
      - "SeqServerUrl=http://seq:5341"
      - "DefinitionsRunningMode=docker"
    depends_on:
      - "mongodb"
      - "identity.bonlinestore.com"
      - "seq"    

  production.bonlinestore.com:
    container_name: production.bonlinestore.com
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - "DatabaseSettings:ConnectionString=mongodb://mongodb:27017"
      - "IdentityServerUrl=https://identity.bonlinestore.com"
      - "SeqServerUrl=http://seq:5341"
      - "ProductionRunningMode=docker"
    depends_on:
      - "mongodb"
      - "identity.bonlinestore.com"
      - "seq"    

  order.bonlinestore.com:
    container_name: order.bonlinestore.com
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - "DatabaseSettings:ConnectionString=mongodb://mongodb:27017"
      - "IdentityServerUrl=https://identity.bonlinestore.com"
      - "SeqServerUrl=http://seq:5341"
      - "OrderRunningMode=docker"
    depends_on:
      - "mongodb"
      - "identity.bonlinestore.com"
      - "seq"    

  gateway.bonlinestore.com:
    container_name: gateway.bonlinestore.com
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80      
      - "IdentityServerUrl=https://identity.bonlinestore.com"
      - "GatewayRunningMode=docker"
    depends_on:
      - "identity.bonlinestore.com"    

  ui.bonlinestore.com:
    container_name: ui.bonlinestore.com
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:      
      - "443:443"
      - "80:80"         

  bff.bonlinestore.com:
    container_name: bff.bonlinestore.com
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80      
      - "DatabaseSettings:ConnectionString=mongodb://mongodb:27017"
      - "IdentityServerUrl=https://identity.bonlinestore.com"
      - "DefinitionsApiUrl=https://definitions.bonlinestore.com"
      - "ProductionApiUrl=https://production.bonlinestore.com"
      - "OrderApiUrl=https://order.bonlinestore.com"
      - "SeqServerUrl=http://seq:5341"
      - "BFFRunningMode=docker" 
    depends_on:
      - "mongodb"
      - "identity.bonlinestore.com"
      - "seq"    
