version: '3.4'

services:
  mongodb:
    image: mongo
  identitydbdocker:
    image: mcr.microsoft.com/mssql/server 
  rabbitmq:
    image: rabbitmq:3.11-management
  seq:
    image: datalust/seq
  definitions.bonlinestore.com:
    image: scakir1978/definitions.bonlinestore.com
    build:
      context: .
      dockerfile: BOnlineStore.Services/Definitions/BOnlineStore.Services.Definitions.Api/Dockerfile  

  order.bonlinestore.com:
    image: scakir1978/order.bonlinestore.com
    build:
      context: .
      dockerfile: BOnlineStore.Services/Order/BOnlineStore.Services.Order.Api/Dockerfile

  production.bonlinestore.com:
    image: scakir1978/production.bonlinestore.com
    build:
      context: .
      dockerfile: BOnlineStore.Services/Production/BOnlineStore.Services.Production.Api/Dockerfile

  identity.bonlinestore.com:
    image: scakir1978/identity.bonlinestore.com
    build:
      context: .
      dockerfile: BOnlineStore.IdentityServer/Dockerfile

  gateway.bonlinestore.com:
    image: scakir1978/gateway.bonlinestore.com
    build:
      context: .
      dockerfile: BOnlineStore.Gateway/Dockerfile  

  ui.bonlinestore.com:
    image: scakir1978/ui.bonlinestore.com
    build:
      context: ./BOnlineStore.UI/ClientApp
      dockerfile: Dockerfile

  bff.bonlinestore.com:
    image: scakir1978/bff.bonlinestore.com
    build:
      context: .
      dockerfile: BOnlineStore.Services/BFF/BOnlineStore.BFF/Dockerfile

volumes:
  mongo_data:
  identity_data:
  rabbitmq_data:
  seq_data:


