version: '3.4'

services:
  mongodb:
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  identitydb:
    container_name: identitydb
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - identity_data:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Scag185489

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"    

  seq:
    container_name: seq
    restart: always
    ports:
      - "80:80"
      - "5341:5341"
    volumes:
      - seq_data:/data
    environment:
      - ACCEPT_EULA=Y        

  bonlinestore.services.definitions.api:
    container_name: definitions.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - "DatabaseSettings:ConnectionString=mongodb://mongodb:27017"
      - "IdentityServerUrl=https://identity.api:5001"
      - "SeqServerUrl=http://seq:5341"
    depends_on:
      - "mongodb"
      - "identityserver.api"
      - "seq"
    ports:
      - "6011:80"
      - "5011:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro        

  bonlinestore.services.production.api:
    container_name: production.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - "DatabaseSettings:ConnectionString=mongodb://mongodb:27017"
      - "IdentityServerUrl=https://identity.api:5001"
      - "SeqServerUrl=http://seq:5341"
    depends_on:
      - "mongodb"
      - "identityserver.api"
      - "seq"
    ports:
      - "6012:80"
      - "5012:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  bonlinestore.services.order.api:
    container_name: order.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - "DatabaseSettings:ConnectionString=mongodb://mongodb:27017"
      - "IdentityServerUrl=https://identity.api:5001"
      - "SeqServerUrl=http://seq:5341"
    depends_on:
      - "mongodb"
      - "identityserver.api"
      - "seq"
    ports:
      - "6013:80"
      - "5013:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  bonlinestore.identityserver:
    container_name: identityserver.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - "ConnectionStrings: DefaultConnection = Server=identitydb,1433;Database=IdentityDB; User=sa; Password=Scag185489"
    depends_on:
      - "identitydb"
    ports:
      - "5001:443"      
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  bonlinestore.ui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
