version: '3.4'

services:
  mongodb:
    image: mongo
  identitydbdocker:
    image: mcr.microsoft.com/mssql/server 
  rabbitmq:
    image: rabbitmq:3.11-management
  seq:
    image: datalust/seq
  bonlinestore.services.definitions.api:
    image: ${DOCKER_REGISTRY-}bonlinestoreservicesdefinitionsapi
    build:
      context: .
      dockerfile: BOnlineStore.Services/Definitions/BOnlineStore.Services.Definitions.Api/Dockerfile  

  bonlinestore.services.order.api:
    image: ${DOCKER_REGISTRY-}bonlinestoreservicesorderapi
    build:
      context: .
      dockerfile: BOnlineStore.Services/Order/BOnlineStore.Services.Order.Api/Dockerfile

  bonlinestore.services.production.api:
    image: ${DOCKER_REGISTRY-}bonlinestoreservicesproductionapi
    build:
      context: .
      dockerfile: BOnlineStore.Services/Production/BOnlineStore.Services.Production.Api/Dockerfile

  bonlinestore.identityserver:
    image: ${DOCKER_REGISTRY-}bonlinestoreidentityserver
    build:
      context: .
      dockerfile: BOnlineStore.IdentityServer/Dockerfile

  bonlinestore.gateway:
    image: ${DOCKER_REGISTRY-}bonlinestoregateway
    build:
      context: .
      dockerfile: BOnlineStore.Gateway/Dockerfile  

  bonlinestore.ui:
    image: ${DOCKER_REGISTRY-}bonlinestoreui
    build:
      context: ./BOnlineStore.UI/ClientApp
      dockerfile: Dockerfile

volumes:
  mongo_data:
  identity_data:
  rabbitmq_data:
  seq_data:

