apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff.bonlinestore.com
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff.bonlinestore.com
  template:
    metadata:
      labels:
        app: bff.bonlinestore.com
    spec:
      containers:
        - name: bff-bonlinestore-com
          image: scakir1978/bff.bonlinestore.com:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512Mi"
              cpu: "128m"
          ports:
            - containerPort: 443
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: bff.bonlinestore.com
                  key: aspnetcore-environment
            - name: ASPNETCORE_URLS
              valueFrom:
                configMapKeyRef:
                  name: bff.bonlinestore.com
                  key: aspnetcore-urls
            - name: IdentityServerUrl
              valueFrom:
                configMapKeyRef:
                  name: bff.bonlinestore.com
                  key: identity-server-url
            - name: DefinitionsApiUrl
              valueFrom:
                configMapKeyRef:
                  name: bff.bonlinestore.com
                  key: definitions-api-url
            - name: ProductionApiUrl
              valueFrom:
                configMapKeyRef:
                  name: bff.bonlinestore.com
                  key: production-api-url
            - name: OrderApiUrl
              valueFrom:
                configMapKeyRef:
                  name: bff.bonlinestore.com
                  key: order-api-url
            - name: SeqServerUrl
              valueFrom:
                configMapKeyRef:
                  name: bff.bonlinestore.com
                  key: seq-server-url
            - name: BffRunningMode
              valueFrom:
                configMapKeyRef:
                  name: bff.bonlinestore.com
                  key: bff-running-mode
---
apiVersion: v1
kind: Service
metadata:
  name: bff-bonlinestore-com
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "bff.bonlinestore.com"
spec:
  selector:
    app: bff.bonlinestore.com
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
