apiVersion: v1
kind: Secret
metadata:
  name: bonlinestore-com-certificate
type: kubernetes.io/tls
data:
  tls.crt: |
    MIIDMzCCAhugAwIBAgIQIJyN+4laxZpLgyYR2T3f/TANBgkqhkiG9w0BAQsFADAd
    MRswGQYDVQQDDBIqLmJvbmxpbmVzdG9yZS5jb20wHhcNMjMwMTEzMDY1MzQxWhcN
    MjQwMTEzMDcxMzQxWjAdMRswGQYDVQQDDBIqLmJvbmxpbmVzdG9yZS5jb20wggEi
    MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCZByXpLx5gYO1IEms1Ycc/jPiZ
    6sQHZ7YCb+ZDd+p8q5VHSsIH3EpFmaQ/DaI875E0EjpH//UAVhE83jXZmYwh9Nca
    7n+migCmOXtYyIIQ52PPjswPN5ksVnn9v25j9V77riBbBrftfguNlTRiJpMGwEzV
    29Vj+T/dj14nRunYtmrY9OUHrKU5OI8SnoJVrwXOiQel2OuanjmMhzEZ4YNsXCoD
    fw60y3sUAO6+s2ycO8W/DHLVhqlhL16bYiMbdoribsTeu1Tlze+n6XVA36jRvuFy
    3VralDTfQDuGWnEF35i6DdufKuciukfWInHvJ9/79NyPR+D4aWEBAEHJkObZAgMB
    AAGjbzBtMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYB
    BQUHAwEwHQYDVR0RBBYwFIISKi5ib25saW5lc3RvcmUuY29tMB0GA1UdDgQWBBTF
    XR/OKJxz73QU5sMo1T2R6ba4CjANBgkqhkiG9w0BAQsFAAOCAQEAl9qT+/UC22rX
    Stuk1LNrO8oecBEXaAY3Sn6SnouF8dwvQsGGrk2AY541759TECRUI3GnUT0ryOl6
    XoMTbxnNe/j1u4PB4U8B1OBG5oDYtCgmNb9OLoNGI6gy7qALXvILOlz+1Pmr/Xv8
    C+ARG/7vWfePt0yFg55dkCxnoiOu72v2Vep/LXiGZYgg9N8jDJXsuyPw2gjOi0ns
    cbWM2xRc41pBlHr2qnjNCo5EyqrbBvdOO7zAZqnrPcjsHMy+fet1uCN0cNu6C3gT
    ZHQBYZ+JAnx4STWTb3Zxjzg77rYfX0BjQ8viM6Rl/YANYPW1lsvYSkjr9Rb5pvsE
    yEpLj46Ojg==
  tls.key: |
    MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCZByXpLx5gYO1I
    Ems1Ycc/jPiZ6sQHZ7YCb+ZDd+p8q5VHSsIH3EpFmaQ/DaI875E0EjpH//UAVhE8
    3jXZmYwh9Nca7n+migCmOXtYyIIQ52PPjswPN5ksVnn9v25j9V77riBbBrftfguN
    lTRiJpMGwEzV29Vj+T/dj14nRunYtmrY9OUHrKU5OI8SnoJVrwXOiQel2OuanjmM
    hzEZ4YNsXCoDfw60y3sUAO6+s2ycO8W/DHLVhqlhL16bYiMbdoribsTeu1Tlze+n
    6XVA36jRvuFy3VralDTfQDuGWnEF35i6DdufKuciukfWInHvJ9/79NyPR+D4aWEB
    AEHJkObZAgMBAAECggEBAIsaIU7/QtiPIwHxpDyJHipZhZ279udYUe2TNDe+KIud
    GPwOK6QjjewIhnG+fexwRIiVzR6nv1jH47F1uHONjQFM47+abrS/G2n+NG53DSw6
    edMxVbK7cmQIU6niOoFoiSe0l7rGt6iNfAj+SPizYdCwOufnhejzqCdJbGe9oVIY
    z98bgsXq3FpXMHL5o6Y/GC2zHQKF1EfLO/b12IZ5loudtMIqw3NO4boyHlKW2cmX
    03IiaY3fPBABBsbfTixz8clwBQu4x+BmBecWPQDLGlwwXx2cgEBiXBDX9VGdkxYy
    V8g+I7kRbqVBT8qneietiq5JQ0KwkHPvBhgJaaEsysUCgYEAxYsyACecIr2fBTf4
    qEEm2vEGZJE321qUpyotpMHiu169qiqT25bRPj14gVdsC3dbmE9+0Dx98u/Cn5UV
    SRGLIUX7SjbtYhO5f4CDALCwTPoVPGobiFfUugHhUjmnIzjJ3EEn5vnpG+F4ab0Z
    Mkz80+jNVdvBLqy88oMgaWflb9cCgYEAxk+vUPiADngYXTWSrd3F7hKu5mK6YSFa
    Uow244mvECfmaG+8rwCOngC2CT+rm1x710JHLt8lAYuI1GQWWXmF3hYfzQ+GDHYn
    TT4aGxB1GSBbKI00SwKoQXPeb491aFm6S489cG5igGXvOzTYxan7WtF/OfPenzJM
    8Tw4BrZBSM8CgYEAvfyvbAKsYaUpKWW5Wmi+q9cfJN2dcPPfAB7KoyhtnXLyypQE
    fC7Csy9/lDW2DhkPGJ9sAW4MW/dHoR9Kx2l9+9RIaAoHqEn8H6pDVAiapo3mmqIa
    NLj0OKjSQbh9DJzzV0e6zqQQE+Z3XoqljwEIL+44fZjKZM9xMXP3Wii4OyUCgYB4
    TvluJwQRQxyM16Z/4m5ky2LeFAE8Ue6o67WU/v98zqgCrd8LUEw1YPsOy1jBrS7Y
    XbYvomKh+FPvfjTs3UOwgz2Ruxw4zSl0u/s8dhSERNPo2xlhdGA9LR1CEwdIYj8Z
    /fFpFx6dBLpI8fucl04NP9FuiBuD+xEgvMbEk6cxkwKBgQCYCHMkqTPHTLBH0YwM
    Er93D0C7IG9tTbVYCUB/3A9RAsXsj8MAWv1qqUb07/AF6oWAOGccn8X3DrPwUDjh
    g4BKf2yS9r4Wj8hRQ5lt7kicjVc/kt/U4XKSCgptVBvob6ZvJ0e092huip1w9X8i
    Of+5EydojLFkWG0H1KFEgiYxYw==
