#****** Bu yaml dosyasý kullanýlarak tls yapýlamadý. Aþaðýdaki komt ile gerçekleþtirildi. ******
#kubectl create secret tls b-online-store-com-certificate --cert=./bonlinestore.crt --key=./bonlinetore-decrypted.key 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    #ingress.kubernetes.io/force-ssl-redirect: "true"
    #nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    #nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    #nginx.ingress.kubernetes.io/proxy-buffering: "on"
    #nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    #nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: bonlinestore-routing
  namespace: default
  labels:
    name: bonlinestore-routing
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ui.b-online-store.com
        - bff.b-online-store.com
        - identity.b-online-store.com
        - definitions.b-online-store.com
        - production.b-online-store.com
        - seq.b-online-store.com
      secretName: bonlinestore-com-certificate
  rules:
    - host: ui.b-online-store.com
      http:
        paths:
          - pathType: Prefix
            path: /(.*)
            backend:
              service:
                name: ui-bonlinestore-com
                port:
                  number: 443
    - host: bff.b-online-store.com
      http:
        paths:
          - pathType: Prefix
            path: /(.*)
            backend:
              service:
                name: bff-bonlinestore-com
                port:
                  number: 443
    - host: definitions.b-online-store.com
      http:
        paths:
          - pathType: Prefix
            path: /(.*)
            backend:
              service:
                name: definitions-bonlinestore-com
                port:
                  number: 443
    - host: production.b-online-store.com
      http:
        paths:
          - pathType: Prefix
            path: /(.*)
            backend:
              service:
                name: production-bonlinestore-com
                port:
                  number: 443
    - host: identity.b-online-store.com
      http:
        paths:
          - pathType: Prefix
            path: /(.*)
            backend:
              service:
                name: identity-bonlinestore-com
                port:
                  number: 443
    - host: seq.b-online-store.com
      http:
        paths:
          - pathType: Prefix
            path: /(.*)
            backend:
              service:
                name: seq
                port:
                  number: 443
