using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BOnlineStore.Localization.Constants
{
    public class DefinitionApiKeys
    {
        public const string ModelGroupCodeNotEmpty = "ModelGroupCodeNotEmpty";
        public const string ModelGroupNameNotEmpty = "ModelGroupNameNotEmpty";
        public const string ModelGroupCodeMustBeUnique = "ModelGroupCodeMustBeUnique";
        public const string ColorCodeNotEmpty = "ColorCodeNotEmpty";
        public const string ColorNameNotEmpty = "ColorNameNotEmpty";
        public const string ColorCodeMustBeUnique = "ColorCodeMustBeUnique";
        public const string ColorGroupNotEmpty = "ColorGroupNotEmpty";
        public const string ColorGroupCodeNotEmpty = "ColorGroupCodeNotEmpty";
        public const string ColorGroupNameNotEmpty = "ColorGroupNameNotEmpty";
        public const string ColorGroupCodeMustBeUnique = "ColorGroupCodeMustBeUnique";
        public const string ModelCodeNotEmpty = "ModelCodeNotEmpty";
        public const string ModelNameNotEmpty = "ModelNameNotEmpty";
        public const string ModelGroupNotEmpty = "ModelGroupNotEmpty";
        public const string ModelCodeMustBeUnique = "ModelCodeMustBeUnique";
        public const string AssemblerNameNotEmpty = "AssemblerNameNotEmpty";
        public const string AssemblerNameMaxLength = "AssemblerNameMaxLength";
        public const string AssemblerCodeNotEmpty = "AssemblerCodeNotEmpty";
        public const string AssemblerCodeMaxLength = "AssemblerCodeMaxLength";
        public const string AssemblerCodeMustBeUnique = "AssemblerCodeMustBeUnique";
        public const string UnitNameNotEmpty = "UnitNameNotEmpty";
        public const string UnitCodeNotEmpty = "UnitCodeNotEmpty";
        public const string UnitCodeMustBeUnique = "UnitCodeMustBeUnique";
        public const string GlassGroupNameNotEmpty = "GlassGroupNameNotEmpty";
        public const string GlassGroupCodeNotEmpty = "GlassGroupCodeNotEmpty";
        public const string GlassGroupCodeMustBeUnique = "GlassGroupCodeMustBeUnique";
        public const string LengthNameNotEmpty = "LengthNameNotEmpty";
        public const string LengthCodeNotEmpty = "LengthCodeNotEmpty";
        public const string LengthCodeMustBeUnique = "LengthCodeMustBeUnique";
        public const string RawMaterialNameNotEmpty = "RawMaterialNameNotEmpty";
        public const string RawMaterialCodeNotEmpty = "RawMaterialCodeNotEmpty";
        public const string RawMaterialCodeMustBeUnique = "RawMaterialCodeMustBeUnique";
        public const string RawMaterialGroupCodeNotEmpty = "RawMaterialGroupCodeNotEmpty";
        public const string RawMaterialGroupNameNotEmpty = "RawMaterialGroupNameNotEmpty";
        public const string RawMaterialGroupCodeMustBeUnique = "RawMaterialGroupCodeMustBeUnique";
        public const string RegionNameNotEmpty = "RegionNameNotEmpty";
        public const string RegionCodeNotEmpty = "RegionCodeNotEmpty";
        public const string RegionCodeMustBeUnique = "RegionCodeCodeMustBeUnique";
        public const string TemplateNameNotEmpty = "TemplateNameNotEmpty";
        public const string TemplateCodeNotEmpty = "TemplateCodeNotEmpty";
        public const string TemplateCodeMustBeUnique = "TemplateCodeMustBeUnique";
        public const string CurrencyNameNotEmpty = "CurrencyNameNotEmpty";
        public const string CurrencyCodeNotEmpty = "CurrencyCodeNotEmpty";
        public const string CurrencyCodeMustBeUnique = "CurrencyCodeMustBeUnique";
        public const string ExpenseNameNotEmpty = "ExpenseNameNotEmpty";
        public const string ExpenseCodeNotEmpty = "ExpenseCodeNotEmpty";
        public const string ExpenseCodeMustBeUnique = "ExpenseCodeMustBeUnique";
        public const string GlassNameNotEmpty = "GlassNameNotEmpty";
        public const string GlassCodeNotEmpty = "GlassCodeNotEmpty";
        public const string GlassCodeMustBeUnique = "GlassCodeMustBeUnique";
        public const string GlassGroupNotEmpty = "GlassGroupNotEmpty";
        public const string BankNameNotEmpty = "BankNameNotEmpty";
        public const string BankCodeNotEmpty = "BankCodeNotEmpty";
        public const string BankCodeMustBeUnique = "BankCodeMustBeUnique";
        public const string FirmTypeNameNotEmpty = "FirmTypeNameNotEmpty";
        public const string FirmTypeCodeNotEmpty = "FirmTypeCodeNotEmpty";
        public const string FirmTypeCodeMustBeUnique = "FirmTypeCodeMustBeUnique";
        public const string RecipeTypeNameNotEmpty = "RecipeTypeNameNotEmpty";
        public const string RecipeTypeCodeNotEmpty = "RecipeTypeCodeNotEmpty";
        public const string RecipeTypeCodeMustBeUnique = "RecipeTypeCodeMustBeUnique";
        public const string PanelNameNotEmpty = "PanelNameNotEmpty";
        public const string PanelCodeNotEmpty = "PanelCodeNotEmpty";
        public const string PanelCodeMustBeUnique = "PanelCodeMustBeUnique";
        public const string MeasurementAssemblyLimitsDayNotEmpty = "MeasurementAssemblyLimitsDayNotEmpty";
        public const string MeasurementAssemblyLimitsAssemblerNotEmpty = "MeasurementAssemblyLimitsAssemblerNotEmpty";
        public const string MeasurementAssemblyLimitsQuantitiesNotEmpty = "MeasurementAssemblyLimitsQuantitiesNotEmpty";
        public const string MeasurementAssemblyLimitsRegionsNotEmpty = "MeasurementAssemblyLimitsRegionsNotEmpty";
        public const string ExchangeRateDateNotEmpty = "ExchangeRateDateNotEmpty";
        public const string CurrencyIdNotEmpty = "CurrencyIdNotEmpty";
        public const string CityNameNotEmpty = "CityNameNotEmpty";
        public const string CityCodeNotEmpty = "CityCodeNotEmpty";
        public const string CityCodeMustBeUnique = "CityCodeMustBeUnique";
        public const string CountyNameNotEmpty = "CountyNameNotEmpty";
        public const string CountyCodeNotEmpty = "CountyCodeNotEmpty";
        public const string CountyCodeMustBeUnique = "CountyCodeMustBeUnique";
        public const string FirmNameNotEmpty = "FirmNameNotEmpty";
        public const string FirmCodeNotEmpty = "FirmCodeNotEmpty";
        public const string FirmCodeMustBeUnique = "FirmCodeMustBeUnique";
        public const string CountryNameNotEmpty = "CountryNameNotEmpty";
        public const string CountryNameMaxLength = "CountryNameMaxLength";
        public const string CountryCodeNotEmpty = "CountryCodeNotEmpty";
        public const string CountryCodeMaxLength = "CountryCodeMaxLength";
        public const string CountryCodeMustBeUnique = "CountryCodeMustBeUnique";
        public const string DistrictNameNotEmpty = "DistrictNameNotEmpty";
        public const string DistrictNameMaxLength = "DistrictNameMaxLength";
        public const string DistrictCodeNotEmpty = "DistrictCodeNotEmpty";
        public const string DistrictCodeMaxLength = "DistrictCodeMaxLength";
        public const string DistrictCodeMustBeUnique = "DistrictCodeMustBeUnique";
    }
}
