# Kubernets dashbooard için gerekli
# kubectl -n kubernetes-dashboard create token admin-user login için gerekli tokenı üretiyor.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: kubernetes-dashboard

