apiVersion: apps/v1
kind: Deployment
metadata:
  name: definitions.bonlinestore.com 
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: definitions.bonlinestore.com
  template:
    metadata:
      labels:
        app: definitions.bonlinestore.com
    spec:
      containers:
        - name: definitions-bonlinestore-com
          image: scakir1978/definitions.bonlinestore.com:latest
          imagePullPolicy: Always          
          ports:
            - containerPort: 443
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: definitions.bonlinestore.com
                  key: aspnetcore-environment
            - name: ASPNETCORE_URLS
              valueFrom:
                configMapKeyRef:
                  name: definitions.bonlinestore.com
                  key: aspnetcore-urls
            - name: IdentityServerUrl
              valueFrom:
                configMapKeyRef:
                  name: definitions.bonlinestore.com
                  key: identity-server-url
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                configMapKeyRef:
                  name: definitions.bonlinestore.com
                  key: definitionsdb-connection-string
            - name: SeqServerUrl
              valueFrom:
                configMapKeyRef:
                  name: definitions.bonlinestore.com
                  key: seq-server-url
            - name: DefinitionsRunningMode
              valueFrom:
                configMapKeyRef:
                  name: definitions.bonlinestore.com
                  key: definitions-running-mode
---
apiVersion: v1
kind: Service
metadata:
  name: definitions-bonlinestore-com
  namespace: default
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "definitions.bonlinestore.com"
spec:
  selector:
    app: definitions.bonlinestore.com
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30411 # NodePort numarasý (30000-32767 aralýðýnda)
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30811 # NodePort numarasý (30000-32767 aralýðýnda)
  type: NodePort
