apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seq
  template:
    metadata:
      labels:
        app: seq
    spec:
      securityContext: # Pod'un güvenlik ayarlarý root user (administrator) olarak çalýþmasýný saðlýyor.
        runAsUser: 0
        runAsGroup: 0
      terminationGracePeriodSeconds: 30
      hostname: seq
      containers:
        - name: seq
          image: datalust/seq:latest
          ports:
            - containerPort: 80
            - containerPort: 5341
          env:
            - name: ACCEPT_EULA
              valueFrom:
                configMapKeyRef:
                  name: seq-configmap
                  key: accept-eula
          volumeMounts:
            - name: seq-volume
              mountPath: /data
      volumes:
        - name: seq-volume
          persistentVolumeClaim:
            claimName: seq-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: seq
  namespace: default
spec:
  selector:
    app: seq
  ports:
  - name: http
    protocol: TCP
    port: 80 # Hizmet portu (küme içi)
    targetPort: 80 # Kapsayýcý portu
    nodePort: 30080 # NodePort numarasý (30000-32767 aralýðýnda)
  - name: events
    protocol: TCP
    port: 5341 # Olay alma hizmeti portu (küme içi)
    targetPort: 5341 # Olay alma kapsayýcý portu
    nodePort: 30341 # NodePort numarasý (30000-32767 aralýðýnda)
  type: NodePort

