apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seq-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  storageClassName: seq-storage
  accessModes:
    - ReadWriteOnce
