apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seq-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce # PV ile ayný eriþim modunu kullanmalý
  resources:
    requests:
      storage: 10Gi # PV ile ayný boyutta depolama alaný talep ediyoruz