apiVersion: apps/v1
kind: Deployment
metadata:
  name: identitydb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identitydb
  template:
    metadata:
      labels:
        app: identitydb
    spec:
      terminationGracePeriodSeconds: 30
      hostname: identitydb
      securityContext:
        fsGroup: 10001
      containers:
        - name: identitydb
          image: mcr.microsoft.com/mssql/server:2019-latest
          resources:
            requests:
              memory: "2G"
              cpu: "2000m"
            limits:
              memory: "2G"
              cpu: "2000m"
          ports:
            - containerPort: 1433
          env:
            - name: MSSQL_PID
              valueFrom:
                configMapKeyRef:
                  name: identitydb-configmap
                  key: mssql-pid
            - name: ACCEPT_EULA
              valueFrom:
                configMapKeyRef:
                  name: identitydb-configmap
                  key: accept-eula
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: identitydb-secret
                  key: mssql-sa-password
          volumeMounts:
            - name: "identitydb-persistent-storage"
              mountPath: /data/bonlinestore/mssql
      volumes:
        - name: "identitydb-persistent-storage"
          persistentVolumeClaim:
            claimName: bonlinestore-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: identitydb
  namespace: default
spec:
  selector:
    app: identitydb
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer
