apiVersion: apps/v1
kind: Deployment
metadata:
  name: identitydb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identitydb
  template:
    metadata:
      labels:
        app: identitydb
    spec:
      securityContext: # Pod'un güvenlik ayarlarý root user (administrator) olarak çalýþmasýný saðlýyor.
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: identitydb
          image: mcr.microsoft.com/mssql/server:2019-latest          
          ports:
            - containerPort: 1433
          env:
            - name: MSSQL_PID
              valueFrom:
                configMapKeyRef:
                  name: identitydb-configmap
                  key: mssql-pid
            - name: ACCEPT_EULA
              valueFrom:
                configMapKeyRef:
                  name: identitydb-configmap
                  key: accept-eula            
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: identitydb-secret
                  key: mssql-sa-password
          volumeMounts:
            - name: sql-volume
              mountPath: /var/opt/mssql
      volumes:
        - name: sql-volume
          persistentVolumeClaim:
            claimName: sql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: identitydb
  namespace: default
spec:
  selector:
    app: identitydb
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 31433 # NodePort numarasý (30000-32767 aralýðýnda)
  type: NodePort
